import { Address, beginCell } from '@ton/core'
import { buildDepositTon, buildTonDepositPayloadCell, buildWithdrawMessage } from '@tonresistor/zkresistor-sdk'
import { describe, expect, it } from 'vitest'
import type { ZkResistorPool } from '../../../shared/ipc-contract/zkresistor'
import { validateZkResistorTransaction } from '../transaction'

const poolAddress = Address.parseRaw(`0:${'11'.repeat(32)}`).toString({ bounceable: true })
const walletAddress = Address.parseRaw(`0:${'22'.repeat(32)}`).toString({ bounceable: false })
const recipientAddress = Address.parseRaw(`0:${'33'.repeat(32)}`).toString({ bounceable: false })
const pool: ZkResistorPool = {
  id: poolAddress,
  address: poolAddress,
  kind: 'ton',
  symbol: 'GRAM',
  name: 'GRAM',
  denomination: '10000000000',
  decimals: 9,
  nextIndex: 0,
  withdrawalCount: 0,
  shieldedDeposits: 0,
  shieldedAmount: '0',
  capacity: 1_048_576,
}
const proofCell = beginCell().storeUint(0, 1).endCell()
const sparseProof = { expectedRoot: 0n, siblingBitmap: 0n, siblings: [] }

describe('validateZkResistorTransaction', () => {
  it('accepts the canonical GRAM deposit generated by the SDK', () => {
    const payload = buildTonDepositPayloadCell({
      fromUser: walletAddress,
      commitment: 1n,
      newRoot: 2n,
      proofCell,
      commitmentSetProof: sparseProof,
    })
    const message = buildDepositTon({
      poolAddress,
      fromUser: walletAddress,
      denomination: BigInt(pool.denomination),
      depositPayload: payload,
    })

    const result = validateZkResistorTransaction(
      {
        operation: 'deposit',
        poolAddress,
        value: message.value.toString(),
        payload: message.payload.toBoc().toString('base64'),
      },
      pool,
      walletAddress
    )

    expect(result.body.equals(message.payload)).toBe(true)
  })

  it('accepts the canonical GRAM withdrawal and extracts its recipient', () => {
    const message = buildWithdrawMessage({
      poolAddress,
      root: 1n,
      nullifierHash: 2n,
      recipient: recipientAddress,
      proofCell,
      nullifierSetProof: sparseProof,
      poolKind: 'ton',
    })

    const result = validateZkResistorTransaction(
      {
        operation: 'withdraw',
        poolAddress,
        value: message.value.toString(),
        payload: message.payload.toBoc().toString('base64'),
      },
      pool,
      walletAddress
    )

    expect(Address.parse(result.recipient ?? '').equals(Address.parse(recipientAddress))).toBe(true)
  })

  it('rejects a mismatched operation or value', () => {
    const payload = buildTonDepositPayloadCell({
      fromUser: walletAddress,
      commitment: 1n,
      newRoot: 2n,
      proofCell,
      commitmentSetProof: sparseProof,
    })

    expect(() =>
      validateZkResistorTransaction(
        { operation: 'withdraw', poolAddress, value: '150000000', payload: payload.toBoc().toString('base64') },
        pool,
        walletAddress
      )
    ).toThrow('wrong operation')
    expect(() =>
      validateZkResistorTransaction(
        { operation: 'deposit', poolAddress, value: '1', payload: payload.toBoc().toString('base64') },
        pool,
        walletAddress
      )
    ).toThrow('does not match')
  })
})
