import {
  BOOKMARKS_CHANNELS,
  BRIDGE_CHANNELS,
  BROWSING_CHANNELS,
  HISTORY_CHANNELS,
  PROXY_CHANNELS,
  SETTINGS_CHANNELS,
  STORAGE_CHANNELS,
  TONCONNECT_CHANNELS,
  WALLET_CONTRACT_CHANNELS,
  WINDOW_CHANNELS,
  CHAT_CHANNELS,
  OVERLAY_CHANNELS,
  COCOON_CHANNELS,
  UPDATER_CHANNELS,
} from './ipc-contract/channels'

// IPC Channel names
export const IPC_CHANNELS = {
  // Proxy
  PROXY_CONNECT: PROXY_CHANNELS.connect,
  PROXY_DISCONNECT: PROXY_CHANNELS.disconnect,
  PROXY_STATUS: PROXY_CHANNELS.status,
  PROXY_PROGRESS: PROXY_CHANNELS.progress,

  // Tabs
  TAB_CREATE: BROWSING_CHANNELS.tabCreate,
  TAB_CLOSE: BROWSING_CHANNELS.tabClose,
  TAB_SWITCH: BROWSING_CHANNELS.tabSwitch,

  // View
  VIEW_HIDE: BROWSING_CHANNELS.viewHide,
  VIEW_SHOW: BROWSING_CHANNELS.viewShow,

  // Navigation
  NAVIGATE: BROWSING_CHANNELS.navigate,
  GO_BACK: BROWSING_CHANNELS.goBack,
  GO_FORWARD: BROWSING_CHANNELS.goForward,
  RELOAD: BROWSING_CHANNELS.reload,
  STOP: BROWSING_CHANNELS.stop,
  ZOOM_GET: BROWSING_CHANNELS.zoomGet,
  ZOOM_SET: BROWSING_CHANNELS.zoomSet,

  // Storage
  STORAGE_ADD_BAG: STORAGE_CHANNELS.addBag,
  STORAGE_REMOVE_BAG: STORAGE_CHANNELS.removeBag,
  STORAGE_LIST_BAGS: STORAGE_CHANNELS.listBags,
  STORAGE_PAUSE_BAG: STORAGE_CHANNELS.pauseBag,
  STORAGE_GET_DETAILS: STORAGE_CHANNELS.getDetails,
  STORAGE_READ_FILE: STORAGE_CHANNELS.readFile,
  STORAGE_OPEN_FOLDER: STORAGE_CHANNELS.openFolder,
  STORAGE_SHOW_FILE: STORAGE_CHANNELS.showFile,

  // Window
  WINDOW_MINIMIZE: WINDOW_CHANNELS.minimize,
  WINDOW_MAXIMIZE: WINDOW_CHANNELS.maximize,
  WINDOW_CLOSE: WINDOW_CHANNELS.close,

  // Settings
  CLEAR_BROWSING_DATA: SETTINGS_CHANNELS.clearBrowsingData,
  STORAGE_GET_DOWNLOAD_PATH: STORAGE_CHANNELS.getDownloadPath,
  STORAGE_SET_DOWNLOAD_PATH: STORAGE_CHANNELS.setDownloadPath,
  STORAGE_SELECT_DOWNLOAD_FOLDER: STORAGE_CHANNELS.selectDownloadFolder,

  // App Settings
  SETTINGS_GET_ALL: SETTINGS_CHANNELS.getAll,
  SETTINGS_GET: SETTINGS_CHANNELS.get,
  SETTINGS_SET: SETTINGS_CHANNELS.set,
  SETTINGS_APPLY: SETTINGS_CHANNELS.apply,
  SETTINGS_RESET: SETTINGS_CHANNELS.reset,
  SETTINGS_DIAGNOSTICS_GET: SETTINGS_CHANNELS.diagnosticsGet,
  SETTINGS_DIAGNOSTICS_ENABLE: SETTINGS_CHANNELS.diagnosticsEnable,
  SETTINGS_DIAGNOSTICS_DISABLE: SETTINGS_CHANNELS.diagnosticsDisable,
  SETTINGS_DIAGNOSTICS_COPY: SETTINGS_CHANNELS.diagnosticsCopy,

  // Sidebar
  UPDATE_SIDEBAR_WIDTH: WINDOW_CHANNELS.sidebarWidth,
  UPDATE_WALLET_SIDEBAR_WIDTH: WINDOW_CHANNELS.walletSidebarWidth,

  // Bookmarks
  BOOKMARKS_LOAD: BOOKMARKS_CHANNELS.load,
  BOOKMARKS_SAVE: BOOKMARKS_CHANNELS.save,

  // History
  HISTORY_CHANGE_MODE: HISTORY_CHANNELS.changeMode,
  HISTORY_SEARCH: HISTORY_CHANNELS.search,
  HISTORY_GET_RECENT: HISTORY_CHANNELS.getRecent,
  HISTORY_GET_TOP: HISTORY_CHANNELS.getTop,
  HISTORY_GET_BY_DATE: HISTORY_CHANNELS.getByDate,
  HISTORY_DELETE: HISTORY_CHANNELS.delete,
  HISTORY_DELETE_BY_DATE: HISTORY_CHANNELS.deleteByDate,
  HISTORY_DELETE_PATTERN: HISTORY_CHANNELS.deletePattern,
  HISTORY_CLEAR: HISTORY_CHANNELS.clear,
  HISTORY_GET_STATS: HISTORY_CHANNELS.getStats,
  HISTORY_HAS_PERSISTENT_FILE: HISTORY_CHANNELS.hasPersistentFile,

  // Updater
  UPDATER_CHECK: UPDATER_CHANNELS.check,
  UPDATER_OPEN_DOWNLOAD_PAGE: UPDATER_CHANNELS.openDownloadPage,

  // Wallet
  WALLET_CREATE: WALLET_CONTRACT_CHANNELS.create,
  WALLET_GET_STATE: WALLET_CONTRACT_CHANNELS.getState,
  WALLET_RETRY_SYSTEM_STORAGE: WALLET_CONTRACT_CHANNELS.retrySystemStorage,
  WALLET_GET_BALANCE: WALLET_CONTRACT_CHANNELS.getBalance,
  WALLET_SEND: WALLET_CONTRACT_CHANNELS.send,
  WALLET_GET_HISTORY: WALLET_CONTRACT_CHANNELS.getHistory,
  WALLET_CLEAR_HISTORY: WALLET_CONTRACT_CHANNELS.clearHistory,
  WALLET_EXPORT_KEY: WALLET_CONTRACT_CHANNELS.exportKey,
  WALLET_APPROVE_PAYMENT: WALLET_CONTRACT_CHANNELS.approvePayment,
  WALLET_REJECT_PAYMENT: WALLET_CONTRACT_CHANNELS.rejectPayment,
  WALLET_PAY_FOR_XHR:
    WALLET_CONTRACT_CHANNELS.payForXhr /* also hardcoded in resources/preload/tonsite.js — keep in sync */,
  WALLET_IMPORT: WALLET_CONTRACT_CHANNELS.importWallet,
  WALLET_DISCOVER_ACCOUNTS: WALLET_CONTRACT_CHANNELS.discoverAccounts,
  WALLET_EXPORT_MNEMONIC: WALLET_CONTRACT_CHANNELS.exportMnemonic,
  WALLET_DELETE: WALLET_CONTRACT_CHANNELS.deleteWallet,
  WALLET_FORGET: WALLET_CONTRACT_CHANNELS.forgetWallet,
  WALLET_UNLOCK: WALLET_CONTRACT_CHANNELS.unlock,
  WALLET_LOCK: WALLET_CONTRACT_CHANNELS.lock,
  WALLET_SETUP_PASSWORD: WALLET_CONTRACT_CHANNELS.setupPassword,
  WALLET_MARK_BACKUP_VERIFIED: WALLET_CONTRACT_CHANNELS.markBackupVerified,
  WALLET_CREATE_BACKUP_CHALLENGE: WALLET_CONTRACT_CHANNELS.createBackupChallenge,
  WALLET_CHANGE_PASSWORD: WALLET_CONTRACT_CHANNELS.changePassword,
  WALLET_SENSITIVE_DISPLAY: WALLET_CONTRACT_CHANNELS.sensitiveDisplay,
  WALLET_RESOLVE_RECIPIENT: WALLET_CONTRACT_CHANNELS.resolveRecipient,
  // Wallet push events (main -> renderer)
  WALLET_BALANCE_UPDATED: WALLET_CONTRACT_CHANNELS.balanceUpdated,
  WALLET_STATE_CHANGED: WALLET_CONTRACT_CHANNELS.stateChanged,
  WALLET_NEW_TRANSACTION: WALLET_CONTRACT_CHANNELS.newTransaction,

  // DNS
  DNS_RESOLVE: WALLET_CONTRACT_CHANNELS.dnsResolve,

  CHAT_CONNECT: CHAT_CHANNELS.connect,
  CHAT_SEND: CHAT_CHANNELS.send,
  CHAT_DM_SEND: CHAT_CHANNELS.dmSend,
  CHAT_MUTATE: CHAT_CHANNELS.mutate,
  CHAT_PENDING: CHAT_CHANNELS.pending,
  CHAT_RETRY_PENDING: CHAT_CHANNELS.retryPending,
  CHAT_DISCARD_PENDING: CHAT_CHANNELS.discardPending,
  CHAT_TIMELINE_BEFORE: CHAT_CHANNELS.timelineBefore,
  CHAT_DISCONNECT: CHAT_CHANNELS.disconnect,
  CHAT_LEAVE: CHAT_CHANNELS.leave,
  CHAT_TIMELINE: CHAT_CHANNELS.timeline,
  CHAT_DM_MESSAGE: CHAT_CHANNELS.dmMessage,
  CHAT_ROOM_STATE: CHAT_CHANNELS.roomState,
  CHAT_ROOM_PRESENCE: CHAT_CHANNELS.roomPresence,
  CHAT_IDENTITY: CHAT_CHANNELS.identity,
  CHAT_IDENTITY_LINK: CHAT_CHANNELS.linkIdentity,
  CHAT_CLAIM_DOMAIN: CHAT_CHANNELS.claimDomain,
  CHAT_PREPARE_DOMAIN_LINK: CHAT_CHANNELS.prepareDomainLink,
  CHAT_OPEN_DOMAIN_LINK: CHAT_CHANNELS.openDomainLink,
  CHAT_CLEAR_DOMAIN: CHAT_CHANNELS.clearDomain,
  CHAT_DETECT_DOMAINS: CHAT_CHANNELS.detectDomains,
  CHAT_RESET_IDENTITY: CHAT_CHANNELS.resetIdentity,

  // Bridge permissions
  BRIDGE_SEND: BRIDGE_CHANNELS.send,
  BRIDGE_MESSAGE: BRIDGE_CHANNELS.message,
  BRIDGE_GET_PERMISSIONS: BRIDGE_CHANNELS.getPermissions,
  BRIDGE_REVOKE_PERMISSION: BRIDGE_CHANNELS.revokePermission,

  // Bridge config
  BRIDGE_GET_CONFIG: BRIDGE_CHANNELS.getConfig,
  BRIDGE_SET_CONFIG: BRIDGE_CHANNELS.setConfig,
  BRIDGE_RESTART: BRIDGE_CHANNELS.restart,

  TONCONNECT_REQUEST: TONCONNECT_CHANNELS.request,
  TONCONNECT_AVAILABILITY: TONCONNECT_CHANNELS.availability,
  TONCONNECT_EVENT: TONCONNECT_CHANNELS.event,
  TONCONNECT_GET_SESSIONS: TONCONNECT_CHANNELS.getSessions,
  TONCONNECT_DISCONNECT_SESSION: TONCONNECT_CHANNELS.disconnectSession,

  // Cocoon AI lifecycle
  COCOON_START: COCOON_CHANNELS.start,
  COCOON_STOP: COCOON_CHANNELS.stop,
  COCOON_STATUS: COCOON_CHANNELS.status,
  COCOON_AVAILABILITY: COCOON_CHANNELS.availability,
  // Cocoon wallet management
  COCOON_WALLET_EXISTS: COCOON_CHANNELS.walletExists,
  COCOON_WALLET_CREATE: COCOON_CHANNELS.walletCreate,
  COCOON_WALLET_INFO: COCOON_CHANNELS.walletInfo,
  COCOON_WALLET_EXPORT_MNEMONIC: COCOON_CHANNELS.walletExportMnemonic,
  COCOON_WALLET_DELETE: COCOON_CHANNELS.walletDelete,
  COCOON_WALLET_MARK_SETUP_COMPLETE: COCOON_CHANNELS.walletMarkSetupComplete,
  // Cocoon setup (owner-funded flow)
  COCOON_SETUP_OWNER_BALANCE: COCOON_CHANNELS.ownerBalance,
  COCOON_SETUP_COCOON_BALANCE: COCOON_CHANNELS.nodeBalance,
  COCOON_SETUP_FUND_COCOON: COCOON_CHANNELS.fund,
  // Cocoon stake lifecycle (atomic primitives — kept for the wizard and debug)
  COCOON_STAKE_INFO: COCOON_CHANNELS.stakeInfo,
  COCOON_STAKE_UNSTAKE: COCOON_CHANNELS.unstake,
  COCOON_STAKE_CASHOUT: COCOON_CHANNELS.cashout,
  // Cocoon composite flows (single-click user actions). flow:stake is the
  // ACTIVATE flow: it transparently archives any prior wallet, rotates to a
  // fresh cocoon_node identity, funds, and stakes — because the upstream
  // proxy worker permanently caches sc_status_ per identity (one cycle per
  // wallet by protocol design).
  COCOON_FLOW_STAKE: COCOON_CHANNELS.flowStake,
  COCOON_FLOW_UNSTAKE: COCOON_CHANNELS.flowUnstake,
  COCOON_FLOW_PENDING: COCOON_CHANNELS.flowPending,
  // Cocoon archive (consumed wallets retained for recovery if upstream worker restarts)
  COCOON_ARCHIVE_LIST: COCOON_CHANNELS.archiveList,
  COCOON_ARCHIVE_EXPORT_MNEMONIC: COCOON_CHANNELS.archiveExportMnemonic,
  // Cocoon recovery (auto-progressed multi-stage drain of an archived wallet's locked client SC)
  COCOON_RECOVERY_ENQUEUE: COCOON_CHANNELS.recoveryEnqueue,
  COCOON_RECOVERY_LIST: COCOON_CHANNELS.recoveryList,
  COCOON_RECOVERY_REMOVE: COCOON_CHANNELS.recoveryRemove,
  COCOON_RECOVERY_ALL: COCOON_CHANNELS.recoveryAll,
  // Cocoon push events (main -> renderer)
  COCOON_STATE_CHANGED: COCOON_CHANNELS.stateChanged,
  COCOON_LOG: COCOON_CHANNELS.log,
  COCOON_WITHDRAW_EVENT: COCOON_CHANNELS.withdrawEvent,
  COCOON_RECOVERY_EVENT: COCOON_CHANNELS.recoveryEvent,

  // Overlay
  OVERLAY_SHOW: OVERLAY_CHANNELS.show,
  OVERLAY_HIDE: OVERLAY_CHANNELS.hide,
  OVERLAY_HIDE_ALL: OVERLAY_CHANNELS.hideAll,
  OVERLAY_UPDATE_BOUNDS: OVERLAY_CHANNELS.updateBounds,
  OVERLAY_ACTION: OVERLAY_CHANNELS.action,

  PAGE_LOADING: BROWSING_CHANNELS.pageLoading,
  PAGE_NAVIGATE: BROWSING_CHANNELS.pageNavigate,
  PAGE_TITLE: BROWSING_CHANNELS.pageTitle,
  PAGE_FAVICON: BROWSING_CHANNELS.pageFavicon,
  PAGE_ZOOM: BROWSING_CHANNELS.pageZoom,
  BROWSER_SHORTCUT: BROWSING_CHANNELS.shortcut,
  CONTEXT_OPEN_LINK: BROWSING_CHANNELS.contextOpenLink,
  PROXY_AUTO_CONNECT: PROXY_CHANNELS.autoConnect,
  STORAGE_BAGS_UPDATED: STORAGE_CHANNELS.bagsUpdated,
  STORAGE_STATUS: STORAGE_CHANNELS.status,
  SETTINGS_CHANGED: SETTINGS_CHANNELS.changed,
  TAB_HISTORY_RESET: BROWSING_CHANNELS.tabHistoryReset,
  WALLET_PAYMENT_REQ: WALLET_CONTRACT_CHANNELS.paymentRequested,
  WALLET_PAYMENT_MADE: WALLET_CONTRACT_CHANNELS.paymentMade,
  WALLET_PAYMENT_FAILED: WALLET_CONTRACT_CHANNELS.paymentFailed,
} as const
