export const THEME_TOKEN_GROUPS = [
  {
    id: 'background',
    keys: ['background', 'backgroundSecondary', 'card', 'muted', 'input'],
  },
  {
    id: 'text',
    keys: ['textPrimary', 'textSecondary', 'heading', 'chromeForeground', 'icon', 'cardForeground'],
  },
  {
    id: 'primaryAccent',
    keys: ['primary', 'primaryForeground', 'accent', 'accentForeground'],
  },
  {
    id: 'secondaryMuted',
    keys: ['secondary', 'secondaryForeground'],
  },
  {
    id: 'statusColors',
    keys: [
      'success',
      'successForeground',
      'warning',
      'warningForeground',
      'destructive',
      'destructiveForeground',
      'info',
      'infoForeground',
    ],
  },
  {
    id: 'borderInput',
    keys: ['border', 'ring'],
  },
] as const

export const THEME_TOKEN_KEYS = THEME_TOKEN_GROUPS.flatMap((group) => group.keys)

export type ThemeColorKey = (typeof THEME_TOKEN_KEYS)[number]
export type ThemeColorValues = Record<ThemeColorKey, string>

export const THEME_TOKEN_CSS_VARIABLES = {
  background: '--background',
  backgroundSecondary: '--background-secondary',
  textPrimary: '--foreground',
  textSecondary: '--muted-foreground',
  heading: '--heading',
  chromeForeground: '--chrome-foreground',
  icon: '--icon',
  card: '--card',
  cardForeground: '--card-foreground',
  primary: '--primary',
  primaryForeground: '--primary-foreground',
  secondary: '--secondary',
  secondaryForeground: '--secondary-foreground',
  accent: '--accent',
  accentForeground: '--accent-foreground',
  muted: '--muted',
  destructive: '--destructive',
  destructiveForeground: '--destructive-foreground',
  success: '--success',
  successForeground: '--success-foreground',
  warning: '--warning',
  warningForeground: '--warning-foreground',
  info: '--info',
  infoForeground: '--info-foreground',
  border: '--border',
  input: '--input',
  ring: '--ring',
} as const satisfies Record<ThemeColorKey, `--${string}`>

export const BUILT_IN_THEME_COLORS = {
  'resistance-dog': {
    background: '213 22% 18%',
    backgroundSecondary: '210 32% 9%',
    textPrimary: '0 0% 96%',
    textSecondary: '210 16% 60%',
    heading: '0 0% 96%',
    chromeForeground: '0 0% 96%',
    icon: '0 0% 96%',
    card: '210 24% 18%',
    cardForeground: '0 0% 96%',
    primary: '200 100% 36%',
    primaryForeground: '0 0% 100%',
    secondary: '210 24% 18%',
    secondaryForeground: '0 0% 96%',
    accent: '200 100% 36%',
    accentForeground: '0 0% 100%',
    muted: '210 22% 15%',
    destructive: '356 75% 52%',
    destructiveForeground: '0 0% 100%',
    success: '145 55% 58%',
    successForeground: '210 32% 9%',
    warning: '38 92% 50%',
    warningForeground: '0 0% 0%',
    info: '199 89% 48%',
    infoForeground: '210 32% 9%',
    border: '210 22% 22%',
    input: '210 24% 18%',
    ring: '200 100% 36%',
  },
  'utya-duck': {
    background: '50 100% 60%',
    backgroundSecondary: '48 100% 55%',
    textPrimary: '0 0% 8%',
    textSecondary: '0 0% 15%',
    heading: '0 0% 8%',
    chromeForeground: '0 0% 8%',
    icon: '0 0% 8%',
    card: '52 100% 65%',
    cardForeground: '0 0% 8%',
    primary: '200 85% 38%',
    primaryForeground: '0 0% 100%',
    secondary: '48 90% 55%',
    secondaryForeground: '0 0% 8%',
    accent: '200 80% 38%',
    accentForeground: '0 0% 100%',
    muted: '48 80% 65%',
    destructive: '0 80% 45%',
    destructiveForeground: '0 0% 100%',
    success: '145 48% 40%',
    successForeground: '0 0% 8%',
    warning: '15 90% 40%',
    warningForeground: '0 0% 100%',
    info: '210 90% 35%',
    infoForeground: '0 0% 100%',
    border: '40 70% 35%',
    input: '52 100% 62%',
    ring: '200 85% 38%',
  },
} as const satisfies Record<'resistance-dog' | 'utya-duck', ThemeColorValues>
