/** Lightweight canonical channel names. Runtime schemas live in domain contracts. */
export const BOOKMARKS_CHANNELS = { load: 'bookmarks:load', save: 'bookmarks:save' } as const
export const WALLET_CONTRACT_CHANNELS = {
  create: 'wallet:create',
  getState: 'wallet:get-state',
  retrySystemStorage: 'wallet:retry-system-storage',
  getBalance: 'wallet:get-balance',
  send: 'wallet:send',
  resolveRecipient: 'wallet:resolve-recipient',
  getHistory: 'wallet:get-history',
  clearHistory: 'wallet:clear-history',
  exportKey: 'wallet:export-key',
  approvePayment: 'wallet:approve-payment',
  rejectPayment: 'wallet:reject-payment',
  payForXhr: 'wallet:pay-for-xhr',
  importWallet: 'wallet:import',
  discoverAccounts: 'wallet:discover-accounts',
  exportMnemonic: 'wallet:export-mnemonic',
  deleteWallet: 'wallet:delete',
  forgetWallet: 'wallet:forget',
  unlock: 'wallet:unlock',
  lock: 'wallet:lock',
  setupPassword: 'wallet:setup-password',
  markBackupVerified: 'wallet:mark-backup-verified',
  createBackupChallenge: 'wallet:create-backup-challenge',
  changePassword: 'wallet:change-password',
  sensitiveDisplay: 'wallet:sensitive-display',
  dnsResolve: 'dns:resolve',
  balanceUpdated: 'wallet:balance-updated',
  stateChanged: 'wallet:state-changed',
  newTransaction: 'wallet:new-transaction',
  paymentRequested: 'wallet:payment-req',
  paymentMade: 'wallet:payment-made',
  paymentFailed: 'wallet:payment-failed',
} as const
export const TONCONNECT_CHANNELS = {
  request: 'tonconnect:request',
  availability: 'tonconnect:availability',
  event: 'tonconnect:event',
  getSessions: 'tonconnect:get-sessions',
  disconnectSession: 'tonconnect:disconnect-session',
} as const
export const SETTINGS_CHANNELS = {
  getAll: 'settings:get-all',
  get: 'settings:get',
  set: 'settings:set',
  apply: 'settings:apply',
  reset: 'settings:reset',
  diagnosticsGet: 'settings:diagnostics:get',
  diagnosticsEnable: 'settings:diagnostics:enable',
  diagnosticsDisable: 'settings:diagnostics:disable',
  diagnosticsCopy: 'settings:diagnostics:copy',
  changed: 'settings:changed',
  clearBrowsingData: 'settings:clear-data',
} as const
export const HISTORY_CHANNELS = {
  changeMode: 'history:change-mode',
  search: 'history:search',
  getRecent: 'history:get-recent',
  getTop: 'history:get-top',
  getByDate: 'history:get-by-date',
  delete: 'history:delete',
  deleteByDate: 'history:delete-by-date',
  deletePattern: 'history:delete-pattern',
  clear: 'history:clear',
  getStats: 'history:get-stats',
  hasPersistentFile: 'history:has-persistent-file',
} as const
export const PROXY_CHANNELS = {
  connect: 'proxy:connect',
  disconnect: 'proxy:disconnect',
  status: 'proxy:status',
  progress: 'proxy:progress',
  autoConnect: 'proxy:auto-connect',
} as const
export const BROWSING_CHANNELS = {
  tabCreate: 'tab:create',
  tabClose: 'tab:close',
  tabSwitch: 'tab:switch',
  viewHide: 'view:hide',
  viewShow: 'view:show',
  navigate: 'navigate',
  goBack: 'go-back',
  goForward: 'go-forward',
  reload: 'reload',
  stop: 'stop',
  zoomGet: 'zoom:get',
  zoomSet: 'zoom:set',
  pageLoading: 'page:loading',
  pageNavigate: 'page:navigate',
  pageTitle: 'page:title',
  pageFavicon: 'page:favicon',
  pageZoom: 'page:zoom',
  shortcut: 'browser:shortcut',
  contextOpenLink: 'context:open-link',
  tabHistoryReset: 'tab:history-reset',
} as const
export const STORAGE_CHANNELS = {
  addBag: 'storage:add-bag',
  removeBag: 'storage:remove-bag',
  listBags: 'storage:list-bags',
  pauseBag: 'storage:pause-bag',
  getDetails: 'storage:get-details',
  readFile: 'storage:read-file',
  openFolder: 'storage:open-folder',
  showFile: 'storage:show-file',
  getDownloadPath: 'storage:get-download-path',
  setDownloadPath: 'storage:set-download-path',
  selectDownloadFolder: 'storage:select-download-folder',
  bagsUpdated: 'storage:bags-updated',
  status: 'storage:status',
} as const
export const BRIDGE_CHANNELS = {
  send: 'bridge:send',
  message: 'bridge:message',
  getPermissions: 'bridge:get-permissions',
  revokePermission: 'bridge:revoke-permission',
  getConfig: 'bridge:get-config',
  setConfig: 'bridge:set-config',
  restart: 'bridge:restart',
} as const
export const WINDOW_CHANNELS = {
  minimize: 'window:minimize',
  maximize: 'window:maximize',
  close: 'window:close',
  sidebarWidth: 'update-sidebar-width',
  walletSidebarWidth: 'update-wallet-sidebar-width',
} as const
export const CHAT_CHANNELS = {
  connect: 'chat:connect',
  send: 'chat:send',
  dmSend: 'chat:dm:send',
  mutate: 'chat:mutate',
  timelineBefore: 'chat:timeline:before',
  disconnect: 'chat:disconnect',
  leave: 'chat:leave',
  timeline: 'chat:timeline',
  dmMessage: 'chat:dm',
  connection: 'chat:connection',
  roomState: 'chat:room-state',
  roomPresence: 'chat:room-presence',
  identity: 'chat:identity',
  identityChanged: 'chat:identity-changed',
  linkIdentity: 'chat:identity:link',
  claimDomain: 'chat:identity:claim-domain',
  clearDomain: 'chat:identity:clear-domain',
  detectDomains: 'chat:identity:detect-domains',
  resetIdentity: 'chat:identity:reset',
} as const
export const OVERLAY_CHANNELS = {
  show: 'overlay:show',
  hide: 'overlay:hide',
  hideAll: 'overlay:hide-all',
  updateBounds: 'overlay:update-bounds',
  action: 'overlay:action',
  content: 'overlay:content',
  theme: 'overlay:theme',
} as const
export const COCOON_CHANNELS = {
  start: 'cocoon:start',
  stop: 'cocoon:stop',
  status: 'cocoon:status',
  availability: 'cocoon:availability',
  walletExists: 'cocoon:wallet:exists',
  walletCreate: 'cocoon:wallet:create',
  walletInfo: 'cocoon:wallet:info',
  walletExportMnemonic: 'cocoon:wallet:export-mnemonic',
  walletDelete: 'cocoon:wallet:delete',
  walletMarkSetupComplete: 'cocoon:wallet:mark-setup-complete',
  ownerBalance: 'cocoon:setup:owner-balance',
  nodeBalance: 'cocoon:setup:cocoon-balance',
  fund: 'cocoon:setup:fund-cocoon',
  stakeInfo: 'cocoon:stake:info',
  unstake: 'cocoon:stake:unstake',
  cashout: 'cocoon:stake:cashout',
  flowStake: 'cocoon:flow:stake',
  flowUnstake: 'cocoon:flow:unstake',
  flowPending: 'cocoon:flow:pending',
  archiveList: 'cocoon:archive:list',
  archiveExportMnemonic: 'cocoon:archive:export-mnemonic',
  recoveryEnqueue: 'cocoon:recovery:enqueue',
  recoveryList: 'cocoon:recovery:list',
  recoveryRemove: 'cocoon:recovery:remove',
  recoveryAll: 'cocoon:recovery:all',
  stateChanged: 'cocoon:state-changed',
  log: 'cocoon:log',
  withdrawEvent: 'cocoon:withdraw:event',
  recoveryEvent: 'cocoon:recovery:event',
} as const
export const UPDATER_CHANNELS = {
  check: 'updater:check',
  openDownloadPage: 'updater:open-download-page',
} as const

/** Lightweight renderer event surface shared with preload; contains no runtime schemas. */
export const MAIN_RENDERER_EVENT_CHANNELS = [
  BROWSING_CHANNELS.pageLoading,
  BROWSING_CHANNELS.pageNavigate,
  BROWSING_CHANNELS.pageTitle,
  BROWSING_CHANNELS.pageFavicon,
  BROWSING_CHANNELS.pageZoom,
  BROWSING_CHANNELS.shortcut,
  BROWSING_CHANNELS.contextOpenLink,
  BROWSING_CHANNELS.tabHistoryReset,
  PROXY_CHANNELS.status,
  PROXY_CHANNELS.progress,
  PROXY_CHANNELS.autoConnect,
  STORAGE_CHANNELS.bagsUpdated,
  STORAGE_CHANNELS.status,
  SETTINGS_CHANNELS.changed,
  WALLET_CONTRACT_CHANNELS.balanceUpdated,
  WALLET_CONTRACT_CHANNELS.stateChanged,
  WALLET_CONTRACT_CHANNELS.newTransaction,
  WALLET_CONTRACT_CHANNELS.paymentRequested,
  WALLET_CONTRACT_CHANNELS.paymentMade,
  WALLET_CONTRACT_CHANNELS.paymentFailed,
  OVERLAY_CHANNELS.action,
  COCOON_CHANNELS.stateChanged,
  COCOON_CHANNELS.log,
  COCOON_CHANNELS.withdrawEvent,
  COCOON_CHANNELS.recoveryEvent,
  CHAT_CHANNELS.timeline,
  CHAT_CHANNELS.dmMessage,
  CHAT_CHANNELS.connection,
  CHAT_CHANNELS.roomState,
  CHAT_CHANNELS.roomPresence,
  CHAT_CHANNELS.identityChanged,
] as const
